config:
  server:     your.irc.server
  nickname:   buildbot
  realname:   buildbot 
  password:   your.irc.server.password(optional) 
  channel:    "#build"
  feed:       http://your.teamcity.build.feed.url 
  verbose:    false
